[package]
name = "auto2048"
version = "0.1.0"
authors = ["Pepijn Dragt <pepijn.dragt@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
sdl2 = {version="0.32.1", features=["ttf","image","gfx","mixer"]}

